# -*- coding: utf-8 -*-
"""Machine failure deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHKHb1ZZ7_G681mFtOA-ieCdLpMxZVPb
"""

import streamlit as st
import pandas as pd
import joblib

st.title("🔧 Machine Failure Prediction App")
st.write("Enter machine parameters to predict if failure will occur.")

# Load the trained pipeline model
try:
    model = joblib.load("random_forest_model.pkl")
    st.success("Model loaded successfully ✅")
except Exception as e:
    st.error(f"⚠️ Could not load model: {e}")
    st.stop()

# Input fields
footfall = st.number_input("Footfall", min_value=0, max_value=10000, value=100)
tempMode = st.selectbox("Temperature Mode", list(range(0,8)))
AQ = st.selectbox("Air Quality (AQ)", list(range(0,8)))
USS = st.selectbox("Ultrasonic Sensor (USS)", list(range(0,8)))
CS = st.selectbox("Cooling System (CS)", list(range(0,8)))
VOC = st.selectbox("VOC Sensor", list(range(0,8)))
RP = st.number_input("Rotational Pressure (RP)", min_value=0, max_value=100, value=30)
IP = st.selectbox("Internal Pressure (IP)", list(range(0,8)))
Temperature = st.number_input("Temperature", min_value=0, max_value=120, value=40)

# Create dataframe for prediction
input_data = pd.DataFrame({
    'footfall': [footfall],
    'tempMode': [tempMode],
    'AQ': [AQ],
    'USS': [USS],
    'CS': [CS],
    'VOC': [VOC],
    'RP': [RP],
    'IP': [IP],
    'Temperature': [Temperature]
})

# Predict button
if st.button("Predict Failure"):
    prediction = model.predict(input_data)[0]
    prob = model.predict_proba(input_data)[0][prediction]
    if prediction == 1:
        st.error(f"⚠️ Machine Failure Predicted! (Confidence: {prob:.2f})")
    else:
        st.success(f"✅ Machine Operating Normally (Confidence: {prob:.2f})")